# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

ignored = ["github.com/dis2/bls12"]

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  version = "~0.1.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "~0.0.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "~0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "~0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.1"

[[override]]
  name = "github.com/tendermint/abci"
  source = "github.com/Project-Arda/abci"
  branch = "tinytx"

[[override]]
  name = "github.com/tendermint/go-crypto"
  source = "github.com/Project-Arda/go-crypto"
  revision = "d5c27796ff5a3f29d02340b6dd735428ee2065af"

[[constraint]]
  version = "~0.7.3"
  source = "github.com/tendermint/go-amino"
  name = "github.com/tendermint/go-wire"

[[constraint]]
  version = "~0.7.0"
  name = "github.com/tendermint/iavl"

[[constraint]]
  version = "~0.18.0-rc1"
  name = "github.com/tendermint/tendermint"

[[override]]
  version = "~0.8.1"
  name = "github.com/tendermint/tmlibs"

[prune]
  go-tests = true
  unused-packages = true
